// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: pocketbikedisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screen_boot
void ui_screen_boot_screen_init(void);
lv_obj_t *ui_screen_boot;
lv_obj_t *ui_boot_label_booting;
void ui_event_boot_button_continue( lv_event_t * e);
lv_obj_t *ui_boot_button_continue;
// CUSTOM VARIABLES


// SCREEN: ui_screen_main
void ui_screen_main_screen_init(void);
void ui_event_screen_main( lv_event_t * e);
lv_obj_t *ui_screen_main;
lv_obj_t *ui_main_arc_arc_battery_percent;
lv_obj_t *ui_main_arc_arc_esc_power;
lv_obj_t *ui_main_container_speed_container;
lv_obj_t *ui_main_label_speed_value;
lv_obj_t *ui_main_label_speed_label;
// CUSTOM VARIABLES


// SCREEN: ui_screen_settings
void ui_screen_settings_screen_init(void);
void ui_event_screen_settings( lv_event_t * e);
lv_obj_t *ui_screen_settings;
// CUSTOM VARIABLES


// SCREEN: ui_screen_profile_editor
void ui_screen_profile_editor_screen_init(void);
void ui_event_screen_profile_editor( lv_event_t * e);
lv_obj_t *ui_screen_profile_editor;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui_startevents____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_boot_button_continue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screen_main_screen_init);
}
}

void ui_event_screen_main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_settings, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_screen_settings_screen_init);
}
}

void ui_event_screen_settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_main, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_screen_main_screen_init);
}
}

void ui_event_screen_profile_editor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_main, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_screen_main_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screen_boot_screen_init();
ui_screen_main_screen_init();
ui_screen_settings_screen_init();
ui_screen_profile_editor_screen_init();
ui_startevents____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screen_boot);
}
