// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: pocketbikedisplay

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_cb_wled_switch(lv_event_t * e);
void ui_cb_wled_brightness_set(lv_event_t * e);
void ui_cb_wled_channel(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
