// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: pocketbikedisplay

#include "ui.h"

void ui_screen_boot_screen_init(void)
{
ui_screen_boot = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_boot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_boot_label_booting = lv_label_create(ui_screen_boot);
lv_obj_set_width( ui_boot_label_booting, 320);
lv_obj_set_height( ui_boot_label_booting, 52);
lv_obj_set_x( ui_boot_label_booting, 34 );
lv_obj_set_y( ui_boot_label_booting, 62 );
lv_obj_set_align( ui_boot_label_booting, LV_ALIGN_CENTER );
lv_label_set_text(ui_boot_label_booting,"Booting...");
lv_obj_set_style_text_align(ui_boot_label_booting, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_boot_label_booting, &ui_font_font_speed_48pt, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_boot_label_booting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_boot_label_booting, 26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_boot_label_booting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_boot_label_booting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_boot_button_continue = lv_btn_create(ui_screen_boot);
lv_obj_set_width( ui_boot_button_continue, 200);
lv_obj_set_height( ui_boot_button_continue, 50);
lv_obj_set_x( ui_boot_button_continue, 0 );
lv_obj_set_y( ui_boot_button_continue, -23 );
lv_obj_set_align( ui_boot_button_continue, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_boot_button_continue, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_boot_button_continue, ui_event_boot_button_continue, LV_EVENT_ALL, NULL);

}
