// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: pocketbikedisplay

#include "ui.h"

void ui_screen_profile_editor_screen_init(void)
{
ui_screen_profile_editor = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_profile_editor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_screen_profile_editor, ui_event_screen_profile_editor, LV_EVENT_ALL, NULL);

}
