// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: pocketbikedisplay

#include "ui.h"

void ui_screen_main_screen_init(void)
{
ui_screen_main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_arc_arc_battery_percent = lv_arc_create(ui_screen_main);
lv_obj_set_width( ui_main_arc_arc_battery_percent, 460);
lv_obj_set_height( ui_main_arc_arc_battery_percent, 460);
lv_obj_set_align( ui_main_arc_arc_battery_percent, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_arc_arc_battery_percent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_value(ui_main_arc_arc_battery_percent, 50);
lv_arc_set_bg_angles(ui_main_arc_arc_battery_percent,110,250);

lv_obj_set_style_bg_color(ui_main_arc_arc_battery_percent, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_arc_arc_battery_percent, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_main_arc_arc_esc_power = lv_arc_create(ui_screen_main);
lv_obj_set_width( ui_main_arc_arc_esc_power, 460);
lv_obj_set_height( ui_main_arc_arc_esc_power, 460);
lv_obj_set_align( ui_main_arc_arc_esc_power, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_arc_arc_esc_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_value(ui_main_arc_arc_esc_power, 50);
lv_arc_set_bg_angles(ui_main_arc_arc_esc_power,290,70);
lv_arc_set_mode(ui_main_arc_arc_esc_power, LV_ARC_MODE_REVERSE);

lv_obj_set_style_pad_left(ui_main_arc_arc_esc_power, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_main_arc_arc_esc_power, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_main_arc_arc_esc_power, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_main_arc_arc_esc_power, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_main_arc_arc_esc_power, lv_color_hex(0xE6A11C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_main_arc_arc_esc_power, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_main_arc_arc_esc_power, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_main_arc_arc_esc_power, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_arc_arc_esc_power, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_main_container_speed_container = lv_obj_create(ui_screen_main);
lv_obj_remove_style_all(ui_main_container_speed_container);
lv_obj_set_width( ui_main_container_speed_container, 239);
lv_obj_set_height( ui_main_container_speed_container, 173);
lv_obj_set_align( ui_main_container_speed_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_main_container_speed_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_label_speed_value = lv_label_create(ui_main_container_speed_container);
lv_obj_set_width( ui_main_label_speed_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_speed_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_speed_value, 0 );
lv_obj_set_y( ui_main_label_speed_value, -25 );
lv_obj_set_align( ui_main_label_speed_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_speed_value,"43");
lv_obj_set_style_text_align(ui_main_label_speed_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_label_speed_value, &ui_font_font_speed_136pt, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_main_label_speed_value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_main_label_speed_value, 26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_main_label_speed_value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_main_label_speed_value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_label_speed_label = lv_label_create(ui_main_container_speed_container);
lv_obj_set_width( ui_main_label_speed_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_speed_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_speed_label, 0 );
lv_obj_set_y( ui_main_label_speed_label, 63 );
lv_obj_set_align( ui_main_label_speed_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_speed_label,"km/h");
lv_obj_set_style_text_align(ui_main_label_speed_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_label_speed_label, &ui_font_font_speed_48pt, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_main_label_speed_label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_main_label_speed_label, 26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_main_label_speed_label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_main_label_speed_label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_screen_main, ui_event_screen_main, LV_EVENT_ALL, NULL);

}
