// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: pocketbikedisplay

#include "ui.h"

void ui_screen_lights_control_screen_init(void)
{
ui_screen_lights_control = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_lights_control, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_screen_lights_control, ui_event_screen_lights_control, LV_EVENT_ALL, NULL);

}
